### ISSUE TITLE
Make satellite contours public?

### ISSUE THREAD

**Issue by MateoV** [mapbox/mapbox-studio-satellite-outdoors.tm2#4]
Any reason not to make this repo and/or https://github.com/mapbox/mapbox-satellite-contours.tm2 public once [updated](https://github.com/mapbox/mapbox-satellite-contours-labels.tm2/issues/3)? Have had a few people ask for the carto.

cc @nickidlugash @ajashton @yhahn @ian29

**Comment by nickidlugash** [comment]
Done.
